#include<stdio.h>
#include<conio.h>

int main()
{
int i;
clrscr();
printf("­Aqu¡ la figura!\n\n");
for(i=1;i<=6;i++){{printf(" ");}} for(i=1;i<=10;i++){{printf("-");}}
printf("\n");
for(i=1;i<=4;i++){{printf(" ");}} for(i=1;i<=2;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=2;i++){{printf("-");}}
printf("\n");
for(i=1;i<=4;i++){{printf(" ");}} for(i=1;i<=2;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=2;i++){{printf("-");}}
printf("\n");
for(i=1;i<=4;i++){{printf(" ");}} for(i=1;i<=2;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=2;i++){{printf("-");}}
printf("\n");
for(i=1;i<=4;i++){{printf(" ");}} for(i=1;i<=2;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=2;i++){{printf("-");}}
printf("\n");
for(i=1;i<=6;i++){{printf(" ");}} for(i=1;i<=10;i++){{printf("-");}}
printf("\n");
for(i=1;i<=6;i++){{printf(" ");}} for(i=1;i<=10;i++){{printf("-");}}
printf("\n");
for(i=1;i<=22;i++){{printf("-");}}
printf("\n");
for(i=1;i<=1;i++){{printf("-");}}
for(i=1;i<=20;i++){{printf(" ");}} for(i=1;i<=1;i++){{printf("-");}}
printf("\n");
for(i=1;i<=1;i++){{printf("-");}} for(i=1;i<=2;i++){{printf(" ");}}
for(i=1;i<=16;i++){{printf("-");}} for(i=1;i<=2;i++){{printf(" ");}}
for(i=1;i<=1;i++){{printf("-");}}
printf("\n");
for(i=1;i<=1;i++){{printf("-");}} for(i=1;i<=2;i++){{printf(" ");}}
for(i=1;i<=16;i++){{printf("-");}} for(i=1;i<=2;i++){{printf(" ");}}
for(i=1;i<=1;i++){{printf("-");}}
printf("\n");
for(i=1;i<=1;i++){{printf("-");}} for(i=1;i<=2;i++){{printf(" ");}}
for(i=1;i<=16;i++){{printf("-");}} for(i=1;i<=2;i++){{printf(" ");}}
for(i=1;i<=1;i++){{printf("-");}}
printf("\n");
for(i=1;i<=1;i++){{printf("-");}} for(i=1;i<=2;i++){{printf(" ");}}
for(i=1;i<=16;i++){{printf("-");}} for(i=1;i<=2;i++){{printf(" ");}}
for(i=1;i<=1;i++){{printf("-");}}
printf("\n");
for(i=1;i<=3;i++){{printf(" ");}} for(i=1;i<=16;i++){{printf("-");}}
printf("\n");
for(i=1;i<=3;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
printf("\n");
for(i=1;i<=3;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
printf("\n");
for(i=1;i<=3;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
printf("\n");
for(i=1;i<=3;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
printf("\n");
for(i=1;i<=3;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
printf("\n");
for(i=1;i<=3;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
for(i=1;i<=10;i++){{printf(" ");}} for(i=1;i<=3;i++){{printf("-");}}
getch();
}